# Generated by Django 3.2.4 on 2021-12-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211001_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourcourse',
        ),
    ]
